nosana:
  description: Nosana-Node Pipeline

global:
  image: registry.hub.docker.com/library/node:lts

  trigger:
    branch:
      - all
      
  environment:
    PINATA_JWT_KEY:
        type: nosana/secret
        endpoint: https://secrets.nosana.ci
        value: PINATA_JWT_KEY

jobs:
  - name: Build and upload to IPFS
    commands:
      - npm ci
      - npm run generate
      - npm run ipfs
