nosana:
  description: Nosana-Node Pipeline

global:
  image: node:18

  trigger:
    branch:
      - all
      
  environment:
    NODE_ENV: ipfs
    PINATA_JWT_KEY:

jobs:
  - name: Build and upload to IPFS
    commands:
      - npm ci
      - npm run generate:ipfs
      - npm run ipfs
